# docker build -f Dockerfile . -t tuxthepenguin84/wudd:latest

services:
  wudd:
    image: tuxthepenguin84/wudd:latest
    container_name: wudd
    restart: unless-stopped
    volumes:
      - ./downloads/:/git/wudd/downloads/
      - ./outputs/:/git/wudd/outputs/
      - ./osinfo.toml:/git/wudd/osinfo.toml:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
